version: '3'

x-superset-image: &superset-image apache/superset:${TAG:-latest-dev}
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

services:
  redis:
    image: redis:latest
    container_name: superset_redis
    restart: unless-stopped
    networks:
      rl:
    volumes:
      - redis:/data
    mem_reservation: 256m
    mem_limit: 512m

  db:
    env_file: docker/.env-non-dev
    image: postgres:10
    container_name: superset_postgres
    restart: unless-stopped
    networks:
      rl:
    volumes:
      - db_home:/var/lib/postgresql/data
    mem_reservation: 256m
    mem_limit: 512m

  superset:
    env_file: docker/.env-non-dev
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    networks:
      rl:
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    mem_reservation: 256m
    mem_limit: 512m

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env-non-dev
    depends_on: *superset-depends-on
    user: "root"
    networks:
      rl:
    volumes: *superset-volumes

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    networks:
      rl:
    volumes: *superset-volumes
    mem_reservation: 1g
    mem_limit: 4g

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    networks:
      rl:
    volumes: *superset-volumes
    mem_reservation: 256m
    mem_limit: 512m

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false

networks:
  rl:
    external: true
    name: rl
